### ISSUE TITLE
Improve module docs, where prudent include tests in examples

### ISSUE THREAD

**Issue by CrowdHailer** [CrowdHailer/OK#13]

**Comment by bill-mybiz** [comment]
What are you wanting to move to the module docs? The readme material?

**Comment by CrowdHailer** [comment]
Some of the readme material. Also move tests to the module docs as well because the work as good examples

**Comment by bill-mybiz** [comment]
I've been wanting to help a bit on the documentation side to clean things up a bit if you're interested. Perhaps by re-organizing the main aspects of the lib?:

1) Concise `with` syntax for `OK.with`.
2) Concise `|>` syntax for tagged result pipelines.
3) Semantic success/failure matching

I say re-organize, because it looks like `OK.with` could be realllly cool. I love Elixir's pattern matching and Erlang's ok/error tagging idiom. It's just one of those things that makes the language(s) awesome. But in `with` statements, they become noisy and the noise reduction really makes for better reading, as well as regains precious horizontal real estate. So I would put the `OK.with` first in the readme (and module docs).

I could just do some stuff for the docs and you could see what you like?

**Comment by CrowdHailer** [comment]
re-organising makes perfect sense. Stuff in the readme is in the order it was created. 

I recon just start a PR with the things that seam most important to change and that'll be easiest to discuss around. I have no attachment to the docs as they stand

**Comment by bill-mybiz** [comment]
Taking this out of the README (from the very end)...looks like notes of things todo? But perhaps this is better left in the issue tracker.

>*Possible extensions to include implementing bind on structs so that errors can be better handled.
> Implement a catch functionality for functions that error.
> Implement existing monad library protocols so can extend similar DB functionality e.g. slick*

**Comment by CrowdHailer** [comment]
this is an open ended issue so will close it and can just tackle PR's on docs for changes as they occur
