### ISSUE TITLE
Raise informative error when not returning correct tuple

### ISSUE THREAD

**Issue by CrowdHailer** [CrowdHailer/OK#14]

**Comment by bill-mybiz** [comment]
Hey @CrowdHailer, I've been trying to comment something in detail for the past couple days but it just ain't working for me (the landlord is remodeling our shower :shower: and it's been a bit hectic!). I love all of the :heart: you're putting into the lib.

FWIW, I have been tinkering off and on (since before the else-block branch was merged), and here is the smallest of things:

```
defp nest([{:<-, _, [left, right]} | rest]) do
  quote do
    case unquote(right) do
      {:ok, unquote(left)} ->
        unquote(nest(rest))
      result = {:error, _} ->
        result
      result ->
        # # Auto-wrap
        # IO.puts "The right side of OK.with statements using the `<-` operator must return values that are tagged either :ok or :error. E.g. {:ok, some_value} or {:error, reason}"
        {:error, result}
        # Raise
        raise InvalidWithStatementError
    end
  end
end

defmodule InvalidWithStatementError do
  defexception message: "The right side of OK.with statements using the `<-` operator must return values that are tagged either :ok or :error. E.g. {:ok, some_value} or {:error, reason}"
end
```

I'm still looking at using it but I need (want?) that ability to auto-wrap badly formatted errors, and I thought it's related to both this and to #12 and #8. I just wanted to go ahead and throw this up here just to give you some feedback/dialog and honestly I've been trying to post something but I've just been interrupted too much. 

Thanks again for all your work for this useful library. :+1:

**Comment by CrowdHailer** [comment]
Hope to work on this this weekend,

[Here](https://github.com/elixir-lang/elixir/blob/dca3df0c031918d822e6f59a8b43bc84fd642239/lib/elixir/lib/exception.ex#L625) is where the did you mean helpers for function errors is generated.

We should be able to do a nice helper so we get.
```
** (BindError) Binding variable failured, due to matchable value `:incorrect`.

      Code
        x <- foo(id)

      Expected signature for foo/1
        foo(id) :: {:ok, x} | {:error, reason}

      Actual values
        foo(5) :: :incorrect
```

**Comment by CrowdHailer** [comment]
See PR #26
