### ISSUE TITLE
Get added to awesome Elixir

### ISSUE THREAD

**Issue by CrowdHailer** [CrowdHailer/OK#16]
I think it's awesome. lets try and get this issue over at [awesome elixir](https://github.com/h4cc/awesome-elixir/issues/1110) closed

**Comment by CrowdHailer** [comment]
add to errors and exception handling and macros section

**Comment by bill-mybiz** [comment]
I wanted to give you some possible descriptions:
---

Straight from the readme:

* [OK](https://github.com/CrowdHailer/OK) - Elegant error handling in Elixir, with result monads.

--- 

In errors section, explicitly state keywords "error", "with", "happy path", and "pipe":

* [OK](https://github.com/CrowdHailer/OK) - Elegant error handling with result monads, featuring a powerfully terse `with` construct and a happy path pipe operator.

---

In macros section, explicitly use "macro". 

* [OK](https://github.com/CrowdHailer/OK) - Macros for elegant happy path coding, maximizing power and readability.

---

I just wanted to list some alternatives.

**Comment by CrowdHailer** [comment]
Like the specific taglines. However I'm not sure if awesome elixir is still being managed from the github repo. Have had no reply to my comments on their issue for OK

**Comment by bill-mybiz** [comment]
I was wondering too, and that is why I was thinking of just doing a PR. If you look at the closed PRs, they are pretty recent, like [this one](https://github.com/h4cc/awesome-elixir/pull/4019).

**Comment by CrowdHailer** [comment]
Maybe that's what I should have done.

**Comment by bill-mybiz** [comment]
Well it's not too late! :laughing:

Did you want to go ahead and do one, or I can do it if you want.

**Comment by CrowdHailer** [comment]
If you have the time go ahead. cheers. :tada:

**Comment by bill-mybiz** [comment]
PR submitted. Hope it helps. :smile:

**Comment by CrowdHailer** [comment]
Thanks @bill-mybiz

**Comment by CrowdHailer** [comment]
I will have to try putting my web framework up eventually

**Comment by bill-mybiz** [comment]
If you're referring to [Raxx](https://github.com/crowdhailer/raxx), I'm sure you could get that added whenever you want. I'm overall for building up from minimal libs, but I personally am terribly ignorant of most things webserver so I can't help much there. Although, :thinking:, I am also looking into another front end to my [ibGib](https://github.com/ibgib/ibgib) engine using Bucklescript, and it may be interesting to have another app in the umbrella with Raxx though. Possibly a stateless web server would be appropriate, as all ibGib happenings are themselves pure functions with the ibGib data records containing append-only immutable data (similar to an event store). It's conceivable I could help you with Raxx's feature set and documentation from the POV of a new user coming to the library. 

Regardless, free free to ping me if you ever want me to proofread any documentation for it. I think the GitHub "review" mechanism allows this? So I think you would do a PR for Raxx, and then ping me in the PR. I would then do a review. Something like that...

My main priority for OK right now is to get rid of those compiler warnings. Since I'm loving it so much, I'm using it ubiquitously now and the warnings are piling up! After that, I was thinking of looking to investigate the guard clauses, as that is a stumbling block wrt refactoring existing native `with` blocks.

You have a motivated believer here in OK for sure! :laughing:

**Comment by CrowdHailer** [comment]
I do mean Raxx (also Tokumei). thanks for the offer of proof reading. 

Don't worry, if you naturally find a place to use it later on, then help with the docs be great. Don't force it tho. It's quite a lot larger project than OK so it's far more beta i.e. still probably will have you rootling around in erlang to debug bits if you use it now. 
I was happy with OK when I released 1.0 I will have to do a bit more work before I get to 1.0 with Raxx
