### ISSUE TITLE
Condense import/require for using both `OK.with` and `~>>`

### ISSUE THREAD

**Issue by bill-mybiz** [CrowdHailer/OK#23]
Currently, to use both `OK.with` and `~>>`, you must do two lines:

```
import OK, only: ["~>>": 2]
require OK
```

The `require OK` is easy to remember, but I personally have to go looking for another file that has the correct `~>>` import statement. I was thinking that this may be a barrier to entry for new users. 

So two questions:

1. Is there a way, possibly with a `use`/`__using__` implementation, that could accomplish this? 
2. Do you even think it's a good idea to do so or are separate lines better?

**Comment by CrowdHailer** [comment]
Elixirs native `with` is a special form an not a macro. therefore it cannot be overwritten and OK cannot be required without specifying an `only` selection. https://elixirforum.com/t/how-to-not-import-with-from-kernel-so-it-can-be-redefined/3876

I think using `__use__` just to specify a special set of imports is not good practise. I think I remember reading something in one of the macro books to this effect but haven't managed to find it a second time.

Adding a FAQ section about why OK cannot have everything imported might be nice because that forum thread has some sublties too it.

p.s. looking at `test/ok_test.exs` I think you can get away with using only the import line

**Comment by bill-mybiz** [comment]
> p.s. looking at test/ok_test.exs I think you can get away with using only the import line

Ah yes, I hadn't realized that. 

> Adding a FAQ section about why OK cannot have everything imported might be nice because that forum thread has some sublties too it.

Yes, I remember reading that thread and I certainly hadn't/haven't gotten all of the nuances. I think since `import OK, only: [~>>: 2, success: 1, failure: 1]` works (I'm not sure how/why this does, but I'm glad it does), just a brief note about the line somewhere in the README seems prudent to me. Perhaps a small code example with both `OK.with` and `~>>` used together as in my PR:

```
# require OK not needed, only the following import
import OK, only: [~>>: 2, success: 1, failure: 1]

iex> OK.with do
...>   a <- {:ok, 100}
...>        ~>> safe_div(10) 
...>        ~>> safe_div(5)
...>   b <- safe_div(64, 32)
...>        ~>> double()
...>   OK.success a + b
...> end
{:ok, 6.0}
```

Maybe without the explanatory comment.

**Comment by CrowdHailer** [comment]
As you found that this is mentioned on the main elixir lang page I'm not going to add a description of require vs import, that belongs elseware in the elixir ecosystem

**Comment by bill-mybiz** [comment]
Yes, I understand not wanting to duplicate that knowledge. I think the small example combining `OK.with` and the `~>>` operator would be sufficient to show how to do the `import` line.
