### ISSUE TITLE
Link to why try catch is a bad idea

### ISSUE THREAD

**Issue by CrowdHailer** [CrowdHailer/OK#28]
catching exceptions has issues will tail recursion. discussed somewhere can't find link. Need to add it to an FAQ on why by default `OK` does not work with exceptions.

**Comment by bill-mybiz** [comment]
I was thinking about this. If the problem has to do with tail recursion, is this when you try to catch the exception at every level of the nested `case` statements produced by `OK.with`? 

I would think that there could be a possible alternative, like `OK.try_with` that is simply syntactic sugar that wraps the entire `OK.with` block in a single `try...catch` statement. I would be very surprised if this would create problems.

Another route would be to have an option flag, possibly related to #12 "options for with" issue, so you could say something like

```elixir
OK.with(rescue/catch: true) do
  # normal statements here, but any exceptions get 
  # converted to error tuple e.g. {:error, {:exception, arithmetic_error}}
  ...
  {:exception, exception} -> 
    # handle exception error
end
```

Note: The `catch: true` would be the implicit square brackets (`[ ]`) that Elixir has.

I am unsure of `rescue` vs. `catch` in this case, but I would lean towards `rescue` as I am thinking specifically about exceptions being raised.

**Comment by seivan** [comment]
@CrowdHailer That sounds like an implementation issue more than an actual problem. I get why we're avoiding exceptions and try to stick with idiomatic (but not compiler(!) enforced) success/error tuples but the user of OK shouldn't have to concern themselves with these things. If a poorly implemented third party libs throws an exception it should just be wrapped as an error tuple and returned in the else block. Anything else is noise. 

At least that's how I see this. I wrote my own Either, so obviously I'm rife with opinion :)

**Comment by seivan** [comment]
This is what should happen
```elixir
{:ok, 6} ~>> Kernel.div(0)
      {:error, "bad argument in arithmetic expression"}
```

If I want it to be thrown and let a supervisor handle it I wouldn't use `OK` piping, so it would make sense that the user would expect it to be managed for them. Just my take.

**Comment by seivan** [comment]
@bill-mybiz @CrowdHailer I take it OK has no intention of making sure exceptions are transformed to error tuples? I'm *guessing* https://github.com/CrowdHailer/OK/pull/25 this tackles that? 

This is something I am interested of as I find Elixir exceptions to be very ambiguous. 
I don't want issues where `method/2` does not exist. That's not my error.
My error is the data I got does not match my expectations. This is one of my main grips with Elixirs standard MO. I get the happy path coding, but the error thrown are ambiguous and not related to the *ACTUAL* issues I need to find out about. 

Which means most of the time I want to capture the exception and make sure it throws the *right* exception which I can than tackle with idiomatic beam/elixir/erlang and handle it with supervisors and logging.

**Comment by CrowdHailer** [comment]
@seivan there are problems with using try catch blocks relating to how erlang manages tail call optimisation, that is my biggest concern with catching errors. also catching every exception raised is rather heavy handed.

The second point is the difference between exceptions from user input/external systems and errors from inaccurate coding.

`Kernal.div(a)` should return `int()` if a is always expected to be non_zero but `{:ok, int()}` if a could be zero. If you have worked on the assumption that `a` is always nonzero then you would like it to raise as it is a coding error.

I'm still very open to exploring options and usecases.

**Comment by bill-mybiz** [comment]
> I take it OK has no intention of making sure exceptions are transformed to error tuples? I'm guessing #25 this tackles that?

#25 has to do with getting rid of a compiler warning that exists because currently the `else` block _always_ adds a clause instead of conditionally adding it. Nothing to do with "exceptions" in the sense that you are talking about, rather that is just the variable name that is used for an error tuple match. (_But it does serve as a reminder that that PR is still open. Perhaps @CrowdHailer could either accept it to resolve #24 or reject it to move forward in a different direction._) 

There seems to be some gray area distinguishing error _paths_ and errors _thrown_. Possibly in hindsight, they should have recommended exceptions be named `MyException` instead of `MyError` when using `defexception` to help to highlight this.

With this in mind...

> Which means most of the time I want to capture the exception and make sure it throws the right exception which I can than tackle with idiomatic beam/elixir/erlang and handle it with supervisors and logging.

With the first "exception", I know you're talking about exceptions proper. But then with "make sure it throws the right exception", do you mean that you would like to wrap it in the error tuple and take it down the unhappy path? Or are you talking about re-throwing an exception proper to "handle it with supervisors and logging"? :confused: If the former, then [my above suggestion](https://github.com/CrowdHailer/OK/issues/28#issuecomment-294955118) (or similar) would take care of it. If the latter, I'm not sure if that is in the purview of this lib?

**Comment by CrowdHailer** [comment]
@seivan @bill-mybiz Eventually I found the reference I was looking for.
Just in source code

>Note that calls inside try/1 are not tail recursive since the VM needs to keep the stacktrace in case an exception happens.

https://github.com/elixir-lang/elixir/blob/22bd10a8170af0b187029d115abe4cc8edcf2ae6/lib/elixir/lib/kernel/special_forms.ex#L1622

I don't think I have a full understanding of all the issues here, might be something I put to the forum at some other time

**Comment by CrowdHailer** [comment]
Added to FAQ
