### ISSUE TITLE
Add when clauses to bind expression

### ISSUE THREAD

**Issue by CrowdHailer** [CrowdHailer/OK#8]
handle when cases in bind

```elixir
OK.try do
  a when is_integer(a) <- safe_div(6, 2)
  b = a + 1
  c <- safe_div(b, 2)
  {:ok, a + c}
end
```

However: 
-  don't want to start throwing match errors in otherwise safe functions.
- can't use when in match expressions and want the bind operation to match the behaviour of a match.

**Comment by CrowdHailer** [comment]
with does have when cases

**Comment by bill-mybiz** [comment]
> can't use when in match expressions and want the bind operation to match the behaviour of a match.

I found this a bit confusing :confused: Could you explain it to me?

I'm finding that guard clauses are the next main focal point of awesomeness for using this lib. Whereas normally I would use a guard in a native `with` block, I am doing things like this:

``` 
  email_identity_ib_gibs <- 
    Authz.get_identities_of_type(identity_ib_gibs, "email")
  :ok <- 
    if length(email_identity_ib_gibs) > 0, do: {:ok, :ok}, else: {:error, :no_email_id}
...
else
  :no_email_id -> 
    emsg = "Current identity has no email identities, and so no oys."
    OK.failure handle_ok_error(emsg, log: true)
```

whereas normally I wouldn't really care about the `:no_email_id` specifier (since I think it's a low-priority error), and I would just put it in a guard:

```
email_identity_ib_gibs when length(email_identity_ib_gibs) > 0 <- 
  Authz.get_identities_of_type(identity_ib_gibs, "email")
```

It's not the end of the world, but does impinge on the sweetness of the construct. (_I definitely prefer `OK.with` without guard clauses over native re"guard"less...ouch._). 

Btw, related to this tangentially, I am actually _enjoying_ refactoring native `with` statements when I'm [hammock-driving](https://github.com/matthiasn/talk-transcripts/blob/master/Hickey_Rich/HammockDrivenDev.md) development of non-trivial problems, i.e. when I'm working on a tough issue and refactoring for a "break". I knew that eliminating `:ok` tuples would reduce noise, but I was not expecting the combination of the `~>>` operator. It's like rediscovering the native `|>` in happy paths! :smile:

**Comment by CrowdHailer** [comment]
Taken off my wish list for OK

**Comment by bill-mybiz** [comment]
That's too bad. Any particular reasoning why this is no longer a goal?

**Comment by CrowdHailer** [comment]
because if you add a when clause that fails to match you will end up returning an {:ok, value} from the error branch.

Also I think that it would be best for `<-` in a with to look as much as possible like a `=` out of a with.

**Comment by bill-mybiz** [comment]
> because if you add a when clause that fails to match you will end up returning an {:ok, value} from the error branch.

Ah, that is an interesting consequence of limiting it to an ok/error-only construct. That is certainly thoroughly consistent thinking (which is a good thing :laughing:)!

> Also I think that it would be best for `<-` in a with to look as much as possible like a `=` out of a with.

"Best" is definitely a difficult term to nail down sometimes. As I mentioned, the utility of the guard is not inconsequential, which is why they added the feature to the native `with` in the first place. The usage of the `<-` operator I think makes it more akin to a `->` operator in `case`, `cond`, etc., which of course has guards. 

Also, still from an adoption POV, others who may refactor their existing code or simply anticipate the functionality may be less enthusiastic to use the lib. 

But after thinking it through, you've swayed me that because `OK.with` is ok/error-only, the guard does not make sense anymore. I was thinking of it strictly as syntactic sugar to eliminate an extra `if` statement, but what would you actually return as the error? A generic "guard failed" error message? 

So, meh. :man_shrugging: Good call on dropping it. :+1:
